name: block_breaker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/textures/board_grid_cell.png
    - assets/textures/board_wall_top.png
    - assets/textures/board_wall_bottom.png
    - assets/textures/board_wall_left.png
    - assets/textures/board_wall_right.png
    - assets/textures/paddle.png
    - assets/textures/block_grey.png
    - assets/textures/block_blue.png
    - assets/textures/block_purple.png
    - assets/textures/block_pink.png
    - assets/textures/block_golden.png

  shaders:
    - assets/shaders/luma.frag
    - assets/shaders/grid.frag
