name: block_breaker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/textures/debug_rectangle.png
    - assets/textures/board_grid_cell.png
    - assets/textures/board_wall_top.png

  shaders:
    - assets/shaders/bloom.frag
    - assets/shaders/grid.frag
